find ID

diff --git a/.github/workflows/branch.yml b/.github/workflows/branch.yml
--- a/.github/workflows/branch.yml
+++ b/.github/workflows/branch.yml
@@ -1,20 +1,31 @@
+name: New Branch Trigger
+
 on:
-  # The issues event below is only needed for the default (auto) mode,
-  # you can remove it otherwise
-  issues:
-    types: [ assigned ]
-  # The issue_comment event below is only needed for the ChatOps mode,
-  # you can remove it otherwise
-  issue_comment:
-    types: [ created ]
-  pull_request:
-    types: [ closed ]
+  create:
+    branches:
+      - 'GH-[0-9]+'
 
 jobs:
-  create_issue_branch_job:
+  my-job:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Create Issue Branch
-        uses: robvanderleek/create-issue-branch@main
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Extract Number
+        id: extract-number
+        run: |
+          BRANCH_NAME=${{ github.ref }}
+          NUMBER_REGEX='GH-([0-9]+)'
+          
+          if [[ $BRANCH_NAME =~ $NUMBER_REGEX ]]; then
+            echo "Extracted Number: ${BASH_REMATCH[1]}"
+            echo "::set-output name=number::${BASH_REMATCH[1]}"
+          else
+            echo "Failed to extract number from branch name"
+            exit 1
+          fi
+
+      #- name: Run a command
+      #  run: echo "This workflow was triggered by the creation of a branch with the specified prefix. Extracted Number: ${{ steps.extract-number.outputs.number }}"
